### ISSUE TITLE
mi_process_info : current RSS negative (v2.2.2)

### ISSUE THREAD

**Issue by davide-digennaro-nozomi** [microsoft/mimalloc#1035]
We have a long-running process (both FreeBSD and linux) that links mimalloc statically and reports memory usage every hour, roughly.

Peak memory is correct, but current_rss sometimes goes negative and never recovers:
this is an excerpt from our log under FreeBSD:

```
Memory: {"current":"18446744020880113664", "peak":"1434853376", "free":"1821986816", "total":"8448888832"}, "CPU": ["3.75%", "7.62%"]}
Memory: {"current":"18446744009594880000", "peak":"1437110272", "free":"1953091584", "total":"8448888832"}, "CPU": ["3.82%", "8.95%"]}
Memory: {"current":"18446743998672453632", "peak":"1443540992", "free":"1852383232", "total":"8448888832"}, "CPU": ["3.51%", "6.51%"]}
```

The first two values come from:
```
 size_t current = 0, peak = 0;
 mi_process_info(nullptr, nullptr, nullptr, &current, &peak, nullptr, nullptr, nullptr);
```

We already tested a patch that was proposed in a PR ([here](https://github.com/microsoft/mimalloc/pull/930)), with no luck.
(but we cherry-picked the PR over v2.17, not over v2.22)

Is there a workaround?
TIA

**Comment by daanx** [comment]
I am looking into it..  it might be due to overestimating the purged (decommitted) amount. A "workaround" may be to disable purging but that would keep the rss as high as the peak.

**Comment by daanx** [comment]
I think this is fixed now in the latest dev branches. (fresh release coming soon)

**Comment by davide-digennaro-nozomi** [comment]
it's still present in v.2.2.3: it does not show up immediately, though

```
EVENT: Memory: {"current":"126296064", "peak":"364666880", "free":"2633515008", "total":"8549060608"}, "CPU": ["0.20%", "0.28%"]}
EVENT: Memory: {"current":"18446744073587662848", "peak":"386363392", "free":"2742247424", "total":"8549060608"}, "CPU": ["0.15%", "0.18%"]}
EVENT: Memory: {"current":"18446744073308545024", "peak":"395870208", "free":"2862145536", "total":"8549060608"}, "CPU": ["0.15%", "0.17%"]}
EVENT: Memory: {"current":"18446744072956682240", "peak":"398008320", "free":"2925563904", "total":"8549060608"}, "CPU": ["0.15%", "0.16%"]}
EVENT: Memory: {"current":"18446744072619433984", "peak":"399749120", "free":"2939203584", "total":"8549060608"}, "CPU": ["0.15%", "0.18%"]}
```
