### ISSUE TITLE
Mimalloc isn't allocating huge pages to factorio on NixOS

### ISSUE THREAD

**Issue by Wolf2482-1639** [microsoft/mimalloc#690]
I run 
LD_PRELOAD=/nix/store/dn2xi29q3lp6w0m59cl1k6rb78l9d7a1-mimalloc-2.0.9/lib/libmimalloc.so MIMALLOC_DECOMMIT_DELAY=10000 MIMALLOC_SHOW_STATS=1 MIMALLOC_SHOW_ERRORS=1 HUGETLB_MORECORE=thp MIMALLOC_RESERVE_HUGE_OS_PAGES=8 /nix/store/z2ccfd9ssizadj5h5xgic74xl65wrqkg-factorio-alpha-1.1.74/bin/factorio --benchmark-ticks 10000 --benchmark-runs 3 --benchmark-sanitize --benchmark ~/.factorio/saves/Twigs\ Game.zip

mimalloc: warning: unable to allocate huge (1GiB) page, trying large (2MiB) pages instead (error 12)
mimalloc: warning: failed to reserve 8 GiB huge pages
mimalloc: warning: unable to allocate huge (1GiB) page, trying large (2MiB) pages instead (error 12)
mimalloc: warning: failed to reserve 8 GiB huge pages
mimalloc: warning: unable to allocate huge (1GiB) page, trying large (2MiB) pages instead (error 12)
mimalloc: warning: failed to reserve 8 GiB huge pages
heap stats:    peak      total      freed    current       unit      count
  reserved:   32.0 MiB   32.0 MiB      0       32.0 MiB
 committed:   32.0 MiB   32.0 MiB      0       32.0 MiB
     reset:      0          0          0          0                            ok
   touched:   64.2 KiB   64.2 KiB  164.6 KiB -100.3 KiB                        ok
  segments:      1          1          0          1                            not all freed!
-abandoned:      0          0          0          0                            ok
   -cached:      0          0          0          0                            ok
     pages:      0          0          2         -2                            ok
-abandoned:      0          0          0          0                            ok
 -extended:      0
 -noretire:      0
     mmaps:      0
   commits:      0
   threads:      0          0          0          0                            ok
  searches:     0.0 avg
numa nodes:       1
   elapsed:       0.004 s
   process: user: 0.004 s, system: 0.001 s, faults: 0, rss: 2.7 MiB, commit: 32.0 MiB
heap stats:    peak      total      freed    current       unit      count
  reserved:      0          0          0          0                            ok
 committed:      0          0          0          0                            ok
     reset:      0          0          0          0                            ok
   touched:      0          0          0          0                            ok
  segments:      0          0          0          0                            ok
-abandoned:      0          0          0          0                            ok
   -cached:      0          0          0          0                            ok
     pages:      0          0          0          0                            ok
-abandoned:      0          0          0          0                            ok
 -extended:      0
 -noretire:      0
     mmaps:      0
   commits:      0
   threads:      0          0          0          0                            ok
  searches:     0.0 avg
numa nodes:       1
   elapsed:       0.009 s
   process: user: 0.002 s, system: 0.002 s, faults: 0, rss: 3.6 MiB
mimalloc: warning: unable to allocate huge (1GiB) page, trying large (2MiB) pages instead (error 12)
mimalloc: warning: failed to reserve 8 GiB huge pages
# factorio benchmark
  Performed 10000 updates in 38091.294 ms
  avg: 3.809 ms, min: 2.947 ms, max: 23.278 ms
  checksum: 3387916432
  Performed 10000 updates in 35988.210 ms
  avg: 3.599 ms, min: 2.862 ms, max: 7.710 ms
  checksum: 3387916432
  Performed 10000 updates in 36191.369 ms
  avg: 3.619 ms, min: 2.889 ms, max: 13.133 ms
  checksum: 3387916432
# end of factorio benchmark
heap stats:    peak      total      freed    current       unit      count
  reserved:    2.0 GiB    2.0 GiB   57.0 MiB    2.0 GiB
 committed:    1.8 GiB    2.3 GiB  506.5 MiB    1.8 GiB
     reset:      0          0          0          0                            ok
   touched:    1.9 MiB    8.3 MiB    8.4 GiB   -8.4 GiB                        ok
  segments:     89        143        135          8                            not all freed!
-abandoned:     10         10         10          0                            ok
   -cached:      0          0          0          0                            ok
     pages:      0          0       85.2 Ki   -85.2 Ki                         ok
-abandoned:     13         13         13          0                            ok
 -extended:      0
 -noretire:      0
     mmaps:      0
   commits:    368
   threads:      3         31         62        -31                            ok
  searches:     0.0 avg
numa nodes:       1
   elapsed:     142.743 s
   process: user: 206.903 s, system: 5.450 s, faults: 0, rss: 1.8 GiB, commit: 1.8 GiB
   
Am I doing something wrong or is this an issue with mimalloc?

**Comment by Wolf2482-1639** [comment]
I'm just dumb, I haven't fixed but now I know I need to allocate hugepages on the os level.

**Comment by daanx** [comment]
It is fixed? Indeed, mimalloc can allocate huge pages only from the OS if it has permission and the OS is configured correctly. How this is done differs per OS, see the readme for some helpful links.

**Comment by Wolf2482-1639** [comment]
It's not fixed but It is broken because I haven't configured stuff so this isn't an actual issue.
