### ISSUE TITLE
libmimalloc fails to build on FreeBSD-arm64

### ISSUE THREAD

**Issue by dmilith** [microsoft/mimalloc#732]
I did `cargo update` on my project using mimalloc, after that I did `cargo build --release` which ends like this:

```
The following warnings were emitted during compilation:

warning: In file included from c_src/mimalloc/src/static.c:37:
warning: In file included from c_src/mimalloc/src/prim/prim.c:22:
warning: c_src/mimalloc/src/prim/unix/prim.c:172:184: error: use of undeclared identifier 'hint'; did you mean 'link'?
warning:         _mi_warning_message("unable to directly request aligned OS memory (error: %d (0x%x), size: 0x%zx bytes, alignment: 0x%zx, hint address: %p)\n", err, err, size, try_alignment, hint);
warning:                                                                                                                                                                                        ^~~~
warning:                                                                                                                                                                                        link
warning: /usr/include/unistd.h:351:6: note: 'link' declared here
warning: int      link(const char *, const char *);
warning:          ^
warning: 1 error generated.

error: failed to run custom build command for `libmimalloc-sys v0.1.32`

Caused by:
  process didn't exit successfully: `/Projects/pff/target/release/build/libmimalloc-sys-bf5afac280c48bd1/build-script-build` (exit status: 1)
  --- stdout
  OPT_LEVEL = Some("z")
  TARGET = Some("aarch64-unknown-freebsd")
  HOST = Some("aarch64-unknown-freebsd")
  cargo:rerun-if-env-changed=CC_aarch64-unknown-freebsd
  CC_aarch64-unknown-freebsd = None
  cargo:rerun-if-env-changed=CC_aarch64_unknown_freebsd
  CC_aarch64_unknown_freebsd = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = Some("cc")
  cargo:rerun-if-env-changed=CFLAGS_aarch64-unknown-freebsd
  CFLAGS_aarch64-unknown-freebsd = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_unknown_freebsd
  CFLAGS_aarch64_unknown_freebsd = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = Some("-w -O3 -fvisibility=default")
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("neon")
  cargo:rerun-if-env-changed=CC_aarch64-unknown-freebsd
  CC_aarch64-unknown-freebsd = None
  cargo:rerun-if-env-changed=CC_aarch64_unknown_freebsd
  CC_aarch64_unknown_freebsd = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = Some("cc")
  cargo:rerun-if-env-changed=CFLAGS_aarch64-unknown-freebsd
  CFLAGS_aarch64-unknown-freebsd = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_unknown_freebsd
  CFLAGS_aarch64_unknown_freebsd = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = Some("-w -O3 -fvisibility=default")
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("neon")
  running: "cc" "-Os" "-ffunction-sections" "-fdata-sections" "-fPIC" "-w" "-O3" "-fvisibility=default" "-I" "c_src/mimalloc/include" "-I" "c_src/mimalloc/src" "-ftls-model=initial-exec" "-DMI_SECURE=4" "-DMI_DEBUG=0" "-o" "/Projects/pff/target/release/build/libmimalloc-sys-4e41c665653f31c8/out/c_src/mimalloc/src/static.o" "-c" "c_src/mimalloc/src/static.c"
  cargo:warning=In file included from c_src/mimalloc/src/static.c:37:
  cargo:warning=In file included from c_src/mimalloc/src/prim/prim.c:22:
  cargo:warning=c_src/mimalloc/src/prim/unix/prim.c:172:184: error: use of undeclared identifier 'hint'; did you mean 'link'?
  cargo:warning=        _mi_warning_message("unable to directly request aligned OS memory (error: %d (0x%x), size: 0x%zx bytes, alignment: 0x%zx, hint address: %p)\n", err, err, size, try_alignment, hint);
  cargo:warning=                                                                                                                                                                                       ^~~~
  cargo:warning=                                                                                                                                                                                       link
  cargo:warning=/usr/include/unistd.h:351:6: note: 'link' declared here
  cargo:warning=int      link(const char *, const char *);
  cargo:warning=         ^
  cargo:warning=1 error generated.
  exit status: 1

  --- stderr


  error occurred: Command "cc" "-Os" "-ffunction-sections" "-fdata-sections" "-fPIC" "-w" "-O3" "-fvisibility=default" "-I" "c_src/mimalloc/include" "-I" "c_src/mimalloc/src" "-ftls-model=initial-exec" "-DMI_SECURE=4" "-DMI_DEBUG=0" "-o" "/Projects/pff/target/release/build/libmimalloc-sys-4e41c665653f31c8/out/c_src/mimalloc/src/static.o" "-c" "c_src/mimalloc/src/static.c" with args "cc" did not execute successfully (status code exit status: 1).
```

**Comment by dmilith** [comment]
p.s. I used version "0.1.29" before without issues, so the issue starts after that release :)

**Comment by devnexen** [comment]
This is issue had been fixed but only on the `dev` branch.

**Comment by daanx** [comment]
Thanks -- I thought the fix was already in the release -- I will make a new release soon!

**Comment by dmilith** [comment]
Can't wait, my Rust builds fail because of this :)

**Comment by daanx** [comment]
hehe, lucky you -- I just pushed a new release (v1.8.2 and v2.1.2). Let me know if it works

**Comment by dmilith** [comment]
@daanx Well, I still see `mimalloc = "0.1.36"` after a fresh `cargo add mimalloc`, so it's the same version? :)

the failure: ```
The following warnings were emitted during compilation:

warning: In file included from c_src/mimalloc/src/static.c:37:
warning: In file included from c_src/mimalloc/src/prim/prim.c:22:
warning: c_src/mimalloc/src/prim/unix/prim.c:172:184: error: use of undeclared identifier 'hint'; did you mean 'link'?
warning:         _mi_warning_message("unable to directly request aligned OS memory (error: %d (0x%x), size: 0x%zx bytes, alignment: 0x%zx, hint address: %p)\n", err, err, size, try_alignment, hint);
warning:                                                                                                                                                                                        ^~~~
warning:                                                                                                                                                                                        link
warning: /usr/include/unistd.h:351:6: note: 'link' declared here
warning: int      link(const char *, const char *);
warning:          ^
warning: 1 error generated.

error: failed to run custom build command for `libmimalloc-sys v0.1.32`

Caused by:
  process didn't exit successfully: `/Projects/certsd-open/target/debug/build/libmimalloc-sys-0e7c8e9a3a7b5bc3/build-script-build` (exit status: 1)
  --- stdout
  OPT_LEVEL = Some("0")
  TARGET = Some("aarch64-unknown-freebsd")
  HOST = Some("aarch64-unknown-freebsd")
  cargo:rerun-if-env-changed=CC_aarch64-unknown-freebsd
  CC_aarch64-unknown-freebsd = None
  cargo:rerun-if-env-changed=CC_aarch64_unknown_freebsd
  CC_aarch64_unknown_freebsd = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = Some("cc")
  cargo:rerun-if-env-changed=CFLAGS_aarch64-unknown-freebsd
  CFLAGS_aarch64-unknown-freebsd = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_unknown_freebsd
  CFLAGS_aarch64_unknown_freebsd = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = Some("-w -O3 -fvisibility=default")
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("neon")
  cargo:rerun-if-env-changed=CC_aarch64-unknown-freebsd
  CC_aarch64-unknown-freebsd = None
  cargo:rerun-if-env-changed=CC_aarch64_unknown_freebsd
  CC_aarch64_unknown_freebsd = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = Some("cc")
  cargo:rerun-if-env-changed=CFLAGS_aarch64-unknown-freebsd
  CFLAGS_aarch64-unknown-freebsd = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_unknown_freebsd
  CFLAGS_aarch64_unknown_freebsd = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = Some("-w -O3 -fvisibility=default")
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("neon")
  running: "sccache" "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "-w" "-O3" "-fvisibility=default" "-I" "c_src/mimalloc/include" "-I" "c_src/mimalloc/src" "-ftls-model=initial-exec" "-DMI_SECURE=4" "-DMI_DEBUG=0" "-o" "/Projects/certsd-open/target/debug/build/libmimalloc-sys-cac4c7b831a34bf5/out/c_src/mimalloc/src/static.o" "-c" "c_src/mimalloc/src/static.c"
  cargo:warning=In file included from c_src/mimalloc/src/static.c:37:
  cargo:warning=In file included from c_src/mimalloc/src/prim/prim.c:22:
  cargo:warning=c_src/mimalloc/src/prim/unix/prim.c:172:184: error: use of undeclared identifier 'hint'; did you mean 'link'?
  cargo:warning=        _mi_warning_message("unable to directly request aligned OS memory (error: %d (0x%x), size: 0x%zx bytes, alignment: 0x%zx, hint address: %p)\n", err, err, size, try_alignment, hint);
  cargo:warning=                                                                                                                                                                                       ^~~~
  cargo:warning=                                                                                                                                                                                       link
  cargo:warning=/usr/include/unistd.h:351:6: note: 'link' declared here
  cargo:warning=int      link(const char *, const char *);
  cargo:warning=         ^
  cargo:warning=1 error generated.
  exit status: 1

  --- stderr


  error occurred: Command "sccache" "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "-w" "-O3" "-fvisibility=default" "-I" "c_src/mimalloc/include" "-I" "c_src/mimalloc/src" "-ftls-model=initial-exec" "-DMI_SECURE=4" "-DMI_DEBUG=0" "-o" "/Projects/certsd-open/target/debug/build/libmimalloc-sys-cac4c7b831a34bf5/out/c_src/mimalloc/src/static.o" "-c" "c_src/mimalloc/src/static.c" with args "cc" did not execute successfully (status code exit status: 1).


warning: build failed, waiting for other jobs to finish...
```

**Comment by devnexen** [comment]
You might need to open a discussion [there](https://github.com/purpleprotocol/mimalloc_rust) instead.

**Comment by daanx** [comment]
Yeah, the rust project needs to update too to the latest version of mimalloc; usually this happens soon though 👍
